### ISSUE TITLE
BUG - the tmdb logo_language_priority configuration for "fr" no longer works

### ISSUE THREAD

**Issue by Derekcde** [CollinHeist/TitleCardMaker#462]
### Installation

Docker - master tag

### Describe the Bug

Hello, 
since the last update I have this error:
```
[INFO] Read preference file "/config/preferences.yml"
[CRITICAL] Invalid TMDb logo language codes - must be comma-separated list of any of the following: "ar", "ar-AE", "ar-SA", "bg", "ca", "cn-CN", "cs", "da", "de-AT", "de-CH", "de-DE", "el", "en", "es-ES", "es-MX", "fa", "fi", "fr-CA", "fr-FR", "he", "hi", "hu", "id", "it-IT", "it-CH", "ja", "ka", "ko", "lb", "lt", "lv", "my", "nb-NO", "nl-BE", "nl-NL", "nn-NO", "ms-BN", "ms-MY", "ms-SG", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sr-RS", "sv-FI", "sv-SE", "th", "tr", "uk", "uz-UZ", "vi", "zh", "zh-CN", "zh-HK", "zh-SG"
[CRITICAL] Preference file is invalid
```

So I tried to put fr-FR but I still get the same error

[**it seems that it dates from this commit**](https://github.com/CollinHeist/TitleCardMaker/commit/4a75eff132a67153804fbbb78b84fcbec39cae00)

On the TMDb site they say, perhaps this would be the cause of the error?: 

> > ISO 3166-1
> You'll usually find our language codes mated to a country code in the format of en-US. The country codes in use here are [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
> 
> 📘
> Note
> 
> Images do not yet support the language-COUNTRY notation. This will be improved in the future. Take a read through the [image language](https://developer.themoviedb.org/docs/image-languages) documentation to learn how to partly get around this limitation.

### Preference File

```yaml
# preferences.yml
options:
  source: /config/source/
  series: /config/yaml/sync_plex_seriestv.yml
  card_type: standard
  episode_data_source: plex
  image_source_priority: plex, tmdb
  filename_format: "{full_name} - S{season:02}E{episode:02} - {title}"
  validate_fonts: true
  season_folder_format: "Season {season:02}"
  sync_specials: true
  language_codes: 
  - fr
plex:
  url: http://xxxxxxx:xxxxxxx/
  verify_ssl: true
  token: xxxxxxxxxxxxx
  watched_style: unique
  unwatched_style: blur
  integrate_with_pmm_overlays: true
  integrate_with_kometa: true
  sync:
    file: /config/yaml/sync_plex_seriestv.yml
    card_directory: /config/cards
    library_name: Séries TV
    mode: match
    compact_mode: true
    add_template: global_template
tautulli:
  url: http://xxxxxx:xxxx/
  verify_ssl: true
  api_key: xxxxxxxxxxxxxxxx
  update_script: /tautulli/update_card.sh
  username: "xxxxx"
  agent_name: Update TitleCardMaker
  script_timeout: 120 
sonarr:
  url: http://xxxx:xxx/
  verify_ssl: true
  api_key: xxxxxxxxxxxxxxxxx
  # sync:
  # - card_directory: /config/cards/
    # downloaded_only: true
    # mode: match
  # - file: /config/yaml/sync_sonarr_seriestv.yml
    # add_template: global_template
tmdb:
  api_key: xxxxxxxxxxxxxxxx
  retry_count: 3
  logo_language_priority: fr
```

### Debug Log

[INFO] Read preference file "/config/preferences.yml"
[CRITICAL] Invalid TMDb logo language codes - must be comma-separated list of any of the following: "ar", "ar-AE", "ar-SA", "bg", "ca", "cn-CN", "cs", "da", "de-AT", "de-CH", "de-DE", "el", "en", "es-ES", "es-MX", "fa", "fi", "fr-CA", "fr-FR", "he", "hi", "hu", "id", "it-IT", "it-CH", "ja", "ka", "ko", "lb", "lt", "lv", "my", "nb-NO", "nl-BE", "nl-NL", "nn-NO", "ms-BN", "ms-MY", "ms-SG", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sr-RS", "sv-FI", "sv-SE", "th", "tr", "uk", "uz-UZ", "vi", "zh", "zh-CN", "zh-HK", "zh-SG"
[CRITICAL] Preference file is invalid
usermod: no changes
[INFO] Read preference file "/config/preferences.yml"
[CRITICAL] Invalid TMDb logo language codes - must be comma-separated list of any of the following: "ar", "ar-AE", "ar-SA", "bg", "ca", "cn-CN", "cs", "da", "de-AT", "de-CH", "de-DE", "el", "en", "es-ES", "es-MX", "fa", "fi", "fr-CA", "fr-FR", "he", "hi", "hu", "id", "it-IT", "it-CH", "ja", "ka", "ko", "lb", "lt", "lv", "my", "nb-NO", "nl-BE", "nl-NL", "nn-NO", "ms-BN", "ms-MY", "ms-SG", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sr-RS", "sv-FI", "sv-SE", "th", "tr", "uk", "uz-UZ", "vi", "zh", "zh-CN", "zh-HK", "zh-SG"
[CRITICAL] Preference file is invalid

**Comment by CollinHeist** [comment]
Transitioning to the `fr-FR` (or `fr-CA`) language code was intentional. Does specifying that instead of just `fr` work for your use?

**Comment by Derekcde** [comment]
no, I tried:

logo_language_priority: fr-FR
logo_language_priority: 'fr-FR'
logo_language_priority: "fr-FR"

**Comment by CollinHeist** [comment]
And what's the problem when you do that?

Edit: Never mind I see in your original post you said you get the same error. Let me look

**Comment by CollinHeist** [comment]
I just pushed a fix onto the develop branch, if you want to grab that and see if it works

**Comment by Derekcde** [comment]
Hi, 
it seems ok, I no longer have an error message with fr-FR
do you know when it will be merged into the master branch?

**Comment by CollinHeist** [comment]
That's good. I would continue using `fr-FR`. That will likely not be merged into master for a while

**Comment by Derekcde** [comment]
ok, thank you for your answers 👍 , I close the issue

**Comment by Derekcde** [comment]
Hi @CollinHeist , it seems that on the develop branch the problem is back.

**Comment by CollinHeist** [comment]
@Derekcde What error are you getting, and what's your setting?

**Comment by CollinHeist** [comment]
Hey I just tested with a clean install of TCM on `develop` and was able to use `fr` in the logo language priority and global language priority settings. Can you provide some more details?

**Comment by Derekcde** [comment]
My first post on this thread talked about a problem with fr which was now fr_FR, but which gave an error.
You made a correction to use fr_FR: https://github.com/CollinHeist/TitleCardMaker/issues/462#issuecomment-2173985677
I have not changed my configuration since our last message, I use "fr-FR", but with the latest dev it no longer works, in fact now we have gone back, it is the "fr" which does not generate no more errors, is this the final config?

**Comment by CollinHeist** [comment]
So both `fr` and `fr-FR` should work (assuming you're talking about the `logo_language_priority` setting, not the `language_codes` setting), but you can try the latest version of `develop` and see if that makes a difference.

**Comment by Derekcde** [comment]
I'm on the latest version of develop and the "fr_FR" is no longer recognized for me, but the "fr" is.
yes I am talking about the logo_langue_priority

**Comment by CollinHeist** [comment]
"fr_FR" is always invalid. You need to try "fr-FR"
